### ISSUE TITLE
reproduce 後のvisualize

### ISSUE THREAD

**Issue by ykyamane** [oist/optinist#377]
workflow をreproduce し、runした後でもvisualize で表示される結果がその前に残っていた
結果になる。

**Comment by emuemuJP** [comment]
概要
problem : visualize after reproduce

重要度
高:

ブランチ名
[visualize-after-visualize](https://github.com/oist/optinist/tree/visualize-after-visualize) -> [develop-main](https://github.com/oist/optinist/tree/develop-main)

期限
~2023/3
