### ISSUE TITLE
CaImAn　でのエラー

### ISSUE THREAD

**Issue by ykyamane** [oist/optinist#378]
多分　CaImAn と　NWB のバージョンが新しくなったせいで
instruction 通りにoptinist をインストールするとCaImAnでエラーになります。

pip install optinist を使わないで以前のバージョンのCaImAn、NWBを使うように手動でインストールすると大丈夫です。

**Comment by emuemuJP** [comment]
概要
problem : install-caiman

重要度
高:

ブランチ名
[install-caiman](https://github.com/oist/optinist/tree/install-caiman) -> [develop-main](https://github.com/oist/optinist/tree/develop-main)

期限
~2023/3

**Comment by itutu-tienday** [comment]
caimanの修正版インストール手順資料を添付。
[Caiman_installation_guide_20230224.pdf](https://github.com/oist/optinist/files/10845480/Caiman_installation_guide_20230224.pdf)

**Comment by itutu-tienday** [comment]
一部環境でエラー発生あり、原因調査のため、reopen.

**Comment by emuemuJP** [comment]
snakemakeから呼び出されたconda環境を使った実行時に、
Caimanの[該当行](https://github.com/flatironinstitute/CaImAn/blob/8f61b060e90cab1888a8112259765f4b38775c47/caiman/motion_correction.py#L3215)のいくつかのworkerで例外が発生してしまいその完了待ちをしてしまうのが原因の様子。
こちらにも関連している様子だが、Caimanレポジトリのコードの修正を待つのは現実的ではない。
この[行](https://github.com/oist/optinist/blob/d3e4febd024b2acd6eebaf6fde4d864e7930d928/optinist/wrappers/caiman_wrapper/motion_correction.py#L22)を
`single_thread=True) `
としてシングルスレッドで実行することで動作することをM2 Mac環境で確認。

**Comment by emuemuJP** [comment]
Windows環境では同対処で問題が解消しないことを確認
以下関数の実行前に既にエラーで終了で終了していることを確認。
https://github.com/oist/optinist/blob/main/optinist/wrappers/caiman_wrapper/motion_correction.py

そのため[snakemake](https://github.com/snakemake/snakemake)のコードに起因する様子。
[run_wrapper](https://github.com/snakemake/snakemake/blob/1fb3cef54dfe877c944b8f38cf4ca78ebe91ebe9/snakemake/executors/__init__.py#L2436)関数内のrunの実行時にエラーが発生している。
このrun関数はpythonの組み込み関数[exec, compile](https://github.com/snakemake/snakemake/blob/1fb3cef54dfe877c944b8f38cf4ca78ebe91ebe9/snakemake/workflow.py#L1236)によって生成されたものになる。
これによって生成された関数は以下となる。
```
def __rule_3(input, output, params, wildcards, threads, resources, log, version, rule, conda_env, container_img, singularity_args, use_singularity, env_modules, bench_record, jobid, is_shell, bench_iteration, cleanup_scripts, shadow_dir, edit_notebook, conda_base_path, basedir, runtime_sourcecache_path, __is_snakemake_rule_func=True):
                                                                        script ( f"{DIRPATH.ROOT_DIR}/api/rules/func.py" , basedir, input, output, params, wildcards, threads, resources, log, config, rule, conda_env, conda_base_path, container_img, singularity_args, env_modules, bench_record, jobid, bench_iteration, cleanup_scripts, shadow_dir, runtime_sourcecache_path
```
どうやら
script関数の中で呼ばれそうなapi/rules/func.pyも実行されていないのでscript関数で落ちている模様。
現在script関数の実態を調査中

**Comment by emuemuJP** [comment]
本エラーは
[self._execute_cmd
](https://github.com/snakemake/snakemake/blob/1fb3cef54dfe877c944b8f38cf4ca78ebe91ebe9/snakemake/script.py#L641)の戻り値がjson形式を想定しているにもかかわらずcaimanのconda環境のactivate時に
```
C:\Projects\optinist-caimanstack>set MKL_NUM_THREADS=1

C:\Projects\optinist-caimanstack>set OPENBLAS_NUM_THREADS=1
```
というメッセージが出力されているために、
[tuple(json.loads(out))](https://github.com/snakemake/snakemake/blob/1fb3cef54dfe877c944b8f38cf4ca78ebe91ebe9/snakemake/script.py#L647)
この関数の実行時に例外が発生してしまっていることが原因。
試しに出力を想定されている`[3, 9]`に変えたところ問題なくcaimanの処理が走ることを確認。
conda activate時にメッセージを出力させない方法を調査する。

**Comment by Reactplus-Hao** [comment]
これまでの提供した手順書では、snakemakeライブラリに幾つかのエラーがあって、対処するのが難しいため、
Dockerを介して、Caimanインストールする方法で手順書を更新いたしました。
弊社の方がMacとWindows環境でビルドした時に、エラーが発生していないことを確認できました。
何度も申し訳ございませんが、ご確認お願い出来ますでしょうか。
[20230316_CaImAn_Installation_Guide.pdf](https://github.com/oist/optinist/files/10997302/20230316_CaImAn_Installation_Guide.pdf)

**Comment by emuemuJP** [comment]
Windows版の不具合についてインストールされたcondaの`activate.bat`内において
```
@echo off
```
コメントを先頭に追記することで環境の切り替え時に落ちてしまう問題に対処可能であることを確認
