### ISSUE TITLE
New ROI detection by LCCD

### ISSUE THREAD

**Issue by emuemuJP** [oist/optinist#382]
**概要**
LCCDは
https://github.com/magnetizedCell/lccd-python
にてopen
Suite2PやCaImAnと違い、ROIの検出部分のみを行うのでその部分で検討が必要
1) lccd へのinput としては motion correction 済みの　ΔF/F を想定
2) lccd からのoutput は roi (それぞれの細胞の領域を０/１で表したもの)のみで、その領域のtimecourseはlccd 外で計算する必要
実際に使うことを考えると、ΔF/F関数とROIを元にしてtime course を計算する部分をこちら(OIST)で用意する必要があります

**重要度**
高

**ブランチ名**
[lccd-roi-detection](https://github.com/oist/optinist/tree/lccd-roi-detection) -> [develop-main](https://github.com/oist/optinist/tree/develop-main)

**関連**
#383 
#410

**期限**
~2022/3

**Comment by ut29** [comment]
Slackで流れそうだったので、最新情報を書いておきます。

LCCDのコード
https://github.com/magnetizedCell/lccd-python
サンプルプログラム
https://github.com/ykyamane/lccd_sample

サンプルを編集していただけるとのことなので、まずは上記サンプルを参考に組み込んでいただくと良いかと思います。
> 結局delta-f-over f を計算する必要がありました。共有したサンプルではtimecourse を raw data のROI部分の平均としていますが、これを delta f over f にするオプションを加えるとよいかと思います。ちょっとサンプルコードを編集します。

**Comment by ut29** [comment]
実行結果を以下に示します。
https://drive.google.com/file/d/1_37U9-GFCUp7uFSxC41hW5DcSmY-Hrly/view
