### ISSUE TITLE
ユニットテスト確認・調整（FE）

### ISSUE THREAD

**Issue by itutu-tienday** [oist/optinist#403]
**概要**
OptiNiSt FrontEndのユニットテストの仕様確認と調整（必要あれば）の適用

**タスク詳細**

- [x] 現行のテストコードの動作確認
  - テストコード格納パス
    - /frontend/src/store/test/
    - /frontend/src/store/\*/\*/\*.test.ts
  - 動作に問題がある場合は、内容調査、調査後の修正、を実施。
- [ ] 現行のテストコードの仕様レビュー
  - 現行テストコードについて、妥当性、カバー率、などの仕様レビューを行う。
  - 改善点が確認された場合は、改善を適用する。

**重要度**
中: この機能は開発要件に含まれているが、早急に対応する必要はない。

**ブランチ名**
TBD

**期限**
2023/3

**関連**
#404

**Comment by Reactplus-Hao** [comment]
@itutu-tienday 

>  現行のテストコードの動作確認

現行のテストコードで開発環境（MacとWindows)で動作が問題ないことを確認できました。
確認結果は下記の添付画像のようです。
<img width="712" alt="Screen Shot 2023-03-24 at 10 18 23" src="https://user-images.githubusercontent.com/87292605/227416683-0146888f-bd90-41db-8b5d-6045189f7372.png">
<img width="888" alt="Screen Shot 2023-03-24 at 10 18 33" src="https://user-images.githubusercontent.com/87292605/227416700-a3d90d61-d1cc-4fe3-8eb5-b5f555eb11d7.png">

> 現行のテストコードの仕様レビューについて、

現行のテストコードがデータ情報向けのテストコードで、弊社のFEの方でデータ構造に変更を行わなかったため、
現行のテストコードでカバーできると思います。

**Comment by itutu-tienday** [comment]
（対応状況メモ）
上記で、現行のテスト仕様確認・動作確認を実施。
テスト項目追加などの改善作業は、別issueにて対応想定。
