### ISSUE TITLE
ユニットテスト確認・調整（BE）

### ISSUE THREAD

**Issue by itutu-tienday** [oist/optinist#404]
**概要**
OptiNiSt BackEndのユニットテストの仕様確認と調整（必要あれば）の適用

**タスク詳細**

- [x] 現行のテストコードの動作確認
  - テストコード格納パス
    - \optinist\tests\
    - ※テスト実行には、optinist リポジトリのルートディレクトリを、PYTHONPATHに通す必要がある。
      - [x] 上記ついて、可能であればコード上での調整（コード上でsys.path を追加する）、または手順の説明をドキュメント化しておく。
  - 動作に問題がある場合は、内容調査、調査後の修正、を実施。
- [x] 現行のテストコードの仕様レビュー
  - 現行テストコードについて、妥当性、カバー率、などの仕様レビューを行う。
  - 改善点が確認された場合は、改善を適用する。

**重要度**
中: この機能は開発要件に含まれているが、早急に対応する必要はない。

**ブランチ名**
[update-be-unittest](https://github.com/oist/optinist/tree/update-be-unittest)

**期限**
2023/3

**関連**
#403

**Comment by Reactplus-Hao** [comment]
既存のテストコードの上で調整した箇所を下記にまとめます。
・optinist/tests/api/snakemake/test_snakemake_setfile.py
このファイルの各関数が実施していますが、まだOutputを確認できていないため、
Outputが要件の通りになっているか確認するためのコードを追加しました。

・optinist/tests/api/experiment/test_expt_writer.py: 
テスト関数でreturnコマンドを実行する時に、条件が正しくない場合、AssertionErrorを出せず、pytestライブラリから警告を出しているため、
pytestライブラリの警告を出さないように、returnコマンドをassertコマンドに変更しました。
上記の修正箇所の以外、他の修正箇所の詳細が必要であれば、教えて頂けますでしょうか。

**Comment by itutu-tienday** [comment]
以下、何点か追加質問を記載します。

- Docker環境で動作を確認されているということですが、開発環境下（Windows、Mac）で動作させるための調整は、どの程度の工数で対応可能でしょうか。
  - ※基本的に、環境変数（OPTINIST_DIR, PYTHONPATH）を設定することで、開発環境下でも動作させられることを想定しています。

- 他、ユニットテストを検証する中で、お気づきの点はありませんでしたでしょうか。（テストに不足がある、etc）

**Comment by Reactplus-Hao** [comment]
> Docker環境で動作を確認されているということですが、開発環境下（Windows、Mac）でユニットテストを動作させるための調整は、どの程度の工数で対応可能でしょうか。

開発環境下（Windows、Mac）でユニットテストを動作させるための調整は、1日ぐらいかかります。
作業内容はテストコードの調整、エラーの確認及び修正（ユニットテストの実施中にエラーが出る場合）となります。

> 他、ユニットテストを検証する中で、お気づきの点はありませんでしたでしょうか。（テストに不足がある、etc）

今回のユニットテストの実施では、主に各ユニットテストを通常に動作できることを確保していますので、Workflow Rename機能のテストコードの追加の以外、他の気付きの点をまだ発見していません。
必要であれば、各機能を詳しくさせて頂きますが、対応工数は0.5日ぐらいかかります。

**Comment by Reactplus-Hao** [comment]
@itutu-tienday 

> 開発環境下（Windows、Mac）でユニットテストを動作させるための調整

- Windows、Macでユニットテストを動作させるため、テストコードを調整して、下記のPRを作成致しました。
    - PRリンク：https://github.com/oist/optinist/pull/481
    - ブランチ名：update-be-unittest
    - 今回の修正では、`pytest`コマンドを実行することで、WindowsとMac環境で直接にテストを実行できることになりました。
       - 備考：幾つかのライブラリを追加しましたので、`pytest`コマンドを実行する前に、`pip install -r requirements.txt`コマンドを実行する必要があります。

> ユニットテストを検証する中で、お気づきの点はありませんでしたでしょうか。（テストに不足がある、etc）

- Windows環境のみで`pytest`コマンドを実行した時、 optinist/tests/api/snakemake/test_snakemake_executor.pyのファイルで下記のエラーが出ています。
"PermissionError: [WinError 32] The process cannot access the file because it is being used by another process" 
    - 原因：error.logファイルがずっと開いているため、他のテスト関数がこのファイルにアクセスできていない
    - 対応方法：ファイルを閉じる下記のコマンドを追加しました。
       - https://github.com/oist/optinist/blob/05be3a92ae620b7767fae1aaa57dc9be8f509c22/optinist/api/logger.py#LL33C15-L33C15

- 下記の部分がテストに不足があります。
   - caiman_wrapper
   - lccd_wrapper
   - optinist_wrapper
   - dummy_wrapper
   - Edit ROI
   - optinist/api/dataclass
   - optinist/api/nwb
上記の部分のテストコードの補足とユニットテスト確認の工数は、3日がかかる見込みとなります。
対応が必要であれば、ご相談ください。

**Comment by itutu-tienday** [comment]
ユニットテストの実行について、以下の手順では、実行エラーが生じました。 （File not found関係）

```bash
cd $OPTINIST_SRC_DIR  # ソースの格納ディレクトリ
cd optinist/tests/
pytest
```

以下のように、OPTINIST_DIR を環境変数に設定すると動作するようでしたが、この手順で合っていますでしょうか。

```bash
export OPTINIST_DIR="$OPTINIST_SRC_DIR/optinist/test_data"
cd $OPTINIST_SRC_DIR  # ソースの格納ディレクトリ
cd optinist/tests/
pytest
```

また上記の他に、必要な設定や手順があれば、情報共有をお願いします。

**Comment by Reactplus-Hao** [comment]
Về phần chạy unit test, trong trình tự dưới đây phát sinh lỗi khi chạy (Liên quan đến File not found）

```
cd $OPTINIST_SRC_DIR  # Directory lưu trữ source
cd optinist/tests/
pytest
```

Nếu setting OPTINIST_DIR vào trong biến số môi trường thì có vẻ có thể hoạt động được. Vậy thì trình tự như dưới đây có đúng k nhỉ? 

```
export OPTINIST_DIR="$OPTINIST_SRC_DIR/optinist/test_data"
cd $OPTINIST_SRC_DIR  # Directory lưu trữ source
cd optinist/tests/
pytest

```
Ngoài ra, ngoài lỗi trên nếu bên mình thấy có phần setting hay trình tự nào cần thiết khác thì hãy chia sẻ cho họ biết.

**Comment by Reactplus-Hao** [comment]
@itutu-tienday 

> ユニットテストの実行について、以下の手順では、実行エラーが生じました。 （File not found関係）
```
cd $OPTINIST_SRC_DIR  # ソースの格納ディレクトリ
cd optinist/tests/
pytest
```

上記の手順について、実行エラーが発生した原因としては、テストコードを含めているディレクトリへ`cd`したためだと思います。

正しい手順は下記のようになりますので、ご確認お願い致します。
```
cd $OPTINIST_SRC_DIR  # ソースの格納ディレクトリ
pytest
```

現時点では、上記の他に、必要な設定や手順が特にありません。

**Comment by itutu-tienday** [comment]
> 現時点では、上記の他に、必要な設定や手順が特にありません。


上記とのことですが、やはり `export OPTINIST_DIR=` で環境変数を設定しない場合、実行エラー（以下添付）が発生しているようです。
※Windows (11), Mac (13) のいずれでも同様

ご確認ください。   ※対応優先度は低

```
$ pytest
======================================= test session starts ========================================
platform darwin -- Python 3.8.16, pytest-7.3.1, pluggy-1.0.0
rootdir: /home/optinist/optinist_develop
configfile: pytest.ini
collected 37 items / 2 errors                                                                      

============================================== ERRORS ==============================================
_____________ ERROR collecting optinist/tests/api/snakemake/test_snakemake_executor.py _____________
optinist/tests/api/snakemake/test_snakemake_executor.py:24: in <module>
    shutil.copyfile(
/Users/iam/mambaforge-pypy3/envs/optinist_20230411/lib/python3.8/shutil.py:264: in copyfile
    with open(src, 'rb') as fsrc, open(dst, 'wb') as fdst:
E   FileNotFoundError: [Errno 2] No such file or directory: '/tmp/optinist/config.yaml'
____________________ ERROR collecting optinist/tests/routers/test_experiment.py ____________________
optinist/tests/routers/test_experiment.py:16: in <module>
    shutil.copytree(
/Users/iam/mambaforge-pypy3/envs/optinist_20230411/lib/python3.8/shutil.py:555: in copytree
    with os.scandir(src) as itr:
E   FileNotFoundError: [Errno 2] No such file or directory: '/tmp/optinist/output_test/0123'
========================================= warnings summary =========================================
../../../../../../Users/iam/mambaforge-pypy3/envs/optinist_20230411/lib/python3.8/site-packages/_pytest/config/__init__.py:1302
  /Users/iam/mambaforge-pypy3/envs/optinist_20230411/lib/python3.8/site-packages/_pytest/config/__init__.py:1302: PytestConfigWarning: Unknown config option: env
  
    self._warn_or_fail_if_strict(f"Unknown config option: {key}\n")

-- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html
===================================== short test summary info ======================================
ERROR optinist/tests/api/snakemake/test_snakemake_executor.py - FileNotFoundError: [Errno 2] No such file or directory: '/tmp/optinist/config.yaml'
ERROR optinist/tests/routers/test_experiment.py - FileNotFoundError: [Errno 2] No such file or directory: '/tmp/optinist/output_test/0123'
!!!!!!!!!!!!!!!!!!!!!!!!!!!!! Interrupted: 2 errors during collection !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
=================================== 1 warning, 2 errors in 6.42s ===================================
```

**Comment by Reactplus-Hao** [comment]
Kh check thì thấy quả nhiên trường hợp không setting biến số môi trường trong `export OPTINIST_DIR=` thì bị lỗi chạy như dưới đây.
※ Cả trong Windows (11) và Mac (13) đều bị vậy.

Nhờ bên mình check giúp ※Độ ưu tiên thấp

```
$ pytest
======================================= test session starts ========================================
platform darwin -- Python 3.8.16, pytest-7.3.1, pluggy-1.0.0
rootdir: /home/optinist/optinist_develop
configfile: pytest.ini
collected 37 items / 2 errors                                                                      

============================================== ERRORS ==============================================
_____________ ERROR collecting optinist/tests/api/snakemake/test_snakemake_executor.py _____________
optinist/tests/api/snakemake/test_snakemake_executor.py:24: in <module>
    shutil.copyfile(
/Users/optinist/mambaforge-pypy3/envs/optinist_20230411/lib/python3.8/shutil.py:264: in copyfile
    with open(src, 'rb') as fsrc, open(dst, 'wb') as fdst:
E   FileNotFoundError: [Errno 2] No such file or directory: '/tmp/optinist/config.yaml'
____________________ ERROR collecting optinist/tests/routers/test_experiment.py ____________________
optinist/tests/routers/test_experiment.py:16: in <module>
    shutil.copytree(
/Users/optinist/mambaforge-pypy3/envs/optinist_20230411/lib/python3.8/shutil.py:555: in copytree
    with os.scandir(src) as itr:
E   FileNotFoundError: [Errno 2] No such file or directory: '/tmp/optinist/output_test/0123'
========================================= warnings summary =========================================
../../../../../../Users/optinist/mambaforge-pypy3/envs/optinist_20230411/lib/python3.8/site-packages/_pytest/config/__init__.py:1302
  /Users/optinist/mambaforge-pypy3/envs/optinist_20230411/lib/python3.8/site-packages/_pytest/config/__init__.py:1302: PytestConfigWarning: Unknown config option: env
  
    self._warn_or_fail_if_strict(f"Unknown config option: {key}\n")

-- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html
===================================== short test summary info ======================================
ERROR optinist/tests/api/snakemake/test_snakemake_executor.py - FileNotFoundError: [Errno 2] No such file or directory: '/tmp/optinist/config.yaml'
ERROR optinist/tests/routers/test_experiment.py - FileNotFoundError: [Errno 2] No such file or directory: '/tmp/optinist/output_test/0123'
!!!!!!!!!!!!!!!!!!!!!!!!!!!!! Interrupted: 2 errors during collection !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
=================================== 1 warning, 2 errors in 6.42s ===================================
```

**Comment by Reactplus-Hao** [comment]
@itutu-tienday 
ライブラリを追加で補足されているため、上記の実行エラーが発生しています。
お手数ですが、下記のコマンドを実行して、再度Requirementsを設定するようにお願い致します。
`pip install -r requirements.txt`

**Comment by itutu-tienday** [comment]
ご指摘にあるように、requirements.txt のインストールが不足していたようです。
上記のインストールにより、エラーが解決されたことを確認しました。

- 残作業
  - 当件は以下のPRのマージ後、マージ実施予定。

**Comment by itutu-tienday** [comment]
不足テストの追加等の改善は、以下の後続issueで対応

- #507
