### ISSUE TITLE
frontendのビルドスクリプトはLinux, Macのみを対象としている

### ISSUE THREAD

**Issue by emuemuJP** [oist/optinist#418]
frontendのビルドスクリプトはLinux, Macのみを対象としている。
そのため、Windows環境でfrontendのビルドで以下のエラーになる。

![image](https://user-images.githubusercontent.com/49627335/223959770-18218761-86bc-4189-8bed-eb144ed0923f.png)

**Comment by emuemuJP** [comment]
以下のようにコマンドを修正することでビルドできる
'set NODE_OPTIONS='--max_old_space_size=4096'

` "build": "set BUILD_PATH=../server/public&& react-scripts --openssl-legacy-provider build",`

**Comment by ShogoAkiyama** [comment]
一応dockerでfrontend buildもできるはず
https://github.com/oist/optinist/blob/main/Makefile#L24-L29
