### ISSUE TITLE
Windows環境でCaiman実行時にエラーログ

### ISSUE THREAD

**Issue by emuemuJP** [oist/optinist#419]
Windows環境でcaiman_mc関数の実行時に添付のエラーログが出る
![image](https://user-images.githubusercontent.com/49627335/224201643-5907e86d-ced0-4e3c-a8a8-36e2301401a3.png)

処理自体は完了する。実行時のWorkflowは以下
![image](https://user-images.githubusercontent.com/49627335/224201995-fa6b24f8-b8ea-4ece-9dd2-55f5b2e28942.png)

**Comment by itutu-tienday** [comment]
以下関連チケットでの検証や改善で、その後 再発は確認されていないため、クローズする。（再発があれば再確認する）

- #446
