### ISSUE TITLE
caiman envにおいてroi editでエラー

### ISSUE THREAD

**Issue by emuemuJP** [oist/optinist#420]
以下のように実行時エラーが起きる
https://user-images.githubusercontent.com/49627335/224203098-86090937-f6dd-47fd-a035-ad05eba2a3eb.mp4

![image](https://user-images.githubusercontent.com/49627335/224205326-2446281c-5745-4743-bc8a-6dffd70b7b79.png)

確認している環境は以下
・Windows（Option2）
・M2 Mac（Option2）

一方でcaimanがOption1で動作しないのでcaimanを実行したいときにroi editが出来ない

**Comment by ut29** [comment]
Ubuntuでも同様の現象を確認した。

**Comment by itutu-tienday** [comment]
以下関連チケットでの検証や改善で、対応済みのため、クローズする。

- #446
