### ISSUE TITLE
ROI Edit_仕様確認 (oist_0320_1-2/3)

### ISSUE THREAD

**Issue by itutu-tienday** [oist/optinist#428]
以下、ROI Edit機能の仕様に関する質問

- どのタイミングで結果が保存されるのか？
- 保存されたnwbの中でどのIDが手動で変更したものなのかはどこを見ればいいのか？

**Comment by emuemuJP** [comment]
> どのタイミングで結果が保存されるのか？
各編集毎に保存される。

> 保存されたnwbの中でどのIDが手動で変更したものなのかはどこを見ればいいのか？
nwbで現在保存されていないので機能追加が必要
