### ISSUE TITLE
CaImAn/NWB problem (oist_0320_5-1)

### ISSUE THREAD

**Issue by itutu-tienday** [oist/optinist#430]
- nwbについて、setting change を行ってからworkflow を走らせるとエラーになる
  - ![nwb_setting_change](https://user-images.githubusercontent.com/122338895/227172424-212e118a-2872-4fcc-98cc-dd07413d77eb.png)

**Comment by emuemuJP** [comment]
再現せず。他に条件がないか要確認。
<img width="1423" alt="スクリーンショット 2023-04-05 1 22 57" src="https://user-images.githubusercontent.com/49627335/229855690-2bd16e36-9dde-4f98-90be-4a8449f030d2.png">

**Comment by emuemuJP** [comment]
最新バージョンでは発生せずとのこと
