### ISSUE TITLE
CaImAn/NWB question (oist_0320_5-2)

### ISSUE THREAD

**Issue by itutu-tienday** [oist/optinist#431]
- acquisitionの下のTwoPohotonSeriesとprocessing/ImageSegmentation/PlaneSegmentation/reference_imagesの下のTwoPohotonSeries,両方作られているが、nwbsettingを変更するとどちらの内容が変更されるのか？

**Comment by emuemuJP** [comment]
どちらも同じobjectなのでnwbsettingを変更するとどちらも変更されるはずである。
しかし現在TwoPhotonSeriesは名前が `TwoPhotonSeries` で以外の場合書き込みに失敗してしまう。
https://github.com/oist/optinist/blob/40bd5300c11b4b17aae14bf4f428521b8ae29bc2/optinist/api/nwb/nwb_creater.py#L65

また、`starting_time`は現在設定しても書き込みがなされていない。

**Comment by emuemuJP** [comment]
以下修正案
```
image_series = TwoPhotonSeries(
    name='TwoPhotonSeries', #config[NWBDATASET.IMAGE_SERIES]['name'],
    starting_frame = starting_frames,
    external_file=image_path,
    imaging_plane=imaging_plane,
    starting_time=float(config[NWBDATASET.IMAGE_SERIES]['starting_time']),
    rate=1.0,
    unit='normalized amplitude'
)
```

**Comment by emuemuJP** [comment]
#473
