### ISSUE TITLE
LCCD problem  (oist_0320_6-1) 

### ISSUE THREAD

**Issue by itutu-tienday** [oist/optinist#432]
caiman_mc→lccdを実行後plotするとcaiman_mc の項目にroisというエントリーが作成されている。これはlccd のroiではないように見える。lccd_cell_detectionの項目のroisは正しいroiになっているように見える。(lccd_rois_in_caiman_mc.png)

<img width="551" alt="lccd_rois_in_caiman_mc" src="https://user-images.githubusercontent.com/122338895/227172905-5221acdd-44dd-4c50-b6f6-b2c6b7fd82ed.png">

**Comment by ReiHashimoto** [comment]
@itutu-tienday 
再現を試してみましたが、問題点を確認できていません。

inputはいずれもsample_data/workflows/input/mouse2p.tiffを使用

1. caiman_mc単体でワークフロー実行
    - caiman_mcのoutput
      ![Image](https://user-images.githubusercontent.com/42664619/234174491-ae0edfc8-1ad6-4011-8428-342d12d0b3f3.png)

2. caiman_mc→lccdのワークフロー実行
    - caiman_mcのoutput（1と変わらず）
      ![Image](https://user-images.githubusercontent.com/42664619/234174653-87fffb65-d5fd-4811-8980-2c485abb787e.png)
    - lccdのoutput
      ![Image](https://user-images.githubusercontent.com/42664619/234174682-8476f7fe-512e-4d01-b287-38c4829e2ee7.png)
  
  
VISUALIZEの際にselectするROIは出力した関数のラベルを元に選択可能になっている仕様で、

- caiman_mcのラベル下のrois → caiman_mcのoutputのROI
- lccd_cell_detectionラベル下のrois→ lccdのoutputのROI

になっており、これらの動作も正常なように見えます。

**Comment by ReiHashimoto** [comment]
#429 のreproduceの件が起因している可能性もあったので、修正前のコミット（33478ecc）にスイッチして検証しても同様

**Comment by ReiHashimoto** [comment]
本件については正常な挙動であることを確認。
一方で、caiman_mcでoutputにROIが含まれることが適切であるかどうかは要確認。
