### ISSUE TITLE
現在実行中のWORKFLOW IDを表示し てほしい (oist_0214_3) 

### ISSUE THREAD

**Issue by itutu-tienday** [oist/optinist#434]
現在実行中のWORKFLOW IDを表示してほしい

《概要》[RECORD]タブから既存のWORKFLOW IDを読み込んだ場合、新たに設
定を加え、[RUN]を実行してしまうと、結果が上書きされてしまう。

《解決案》
・[WORKFLOW]画面内に現在のタスクIDを表示。
・実行結果を上書きしても良いか確認する。

《仕様確認》[RUN ALL]を選択すると新規IDとして登録される

**Comment by ReiHashimoto** [comment]
## 実装方針（検討中）
### UI
- 表示項目
  - ID, 名前
- 表示位置
    - SNAKEMAKEなどのボタンの行の左端
- スタイル
    - ラベルはID

### 表示条件
- RUN_ALL実行前: IDがないため非表示
- RUN_ALL実行後: APIレスポンスから取得したIDを表示
- RECORDからREPRODUCEをクリック後: ReproduceしたレコードのIDを表示
- ID表示状態でパラメータの変更があった場合
    - アラートを出す/出さない
        - キャンセルで元に戻す/戻さない
    - IDを非表示
    - RUNを実行不可にする（RUN_ALL)のみ
        - REPRODUCEの状態から変わった場合には強制的にRUN_ALL扱い
    - どこまでがパラメータの変更に含まれるか --> コードを調査して検知のしやすさ・工数で判断
      - 一律パターン
      - ノードの座標の変更は許容
          - 関数
          - inputファイル
          - SNAKEMAKE settings
          - NWB settings

**Comment by itutu-tienday** [comment]
（メモ）
- Visualize画面でも、IDを確認できるとよい。
