### ISSUE TITLE
新規WORKFLOW IDの作成機能 (oist_0214_4)

### ISSUE THREAD

**Issue by itutu-tienday** [oist/optinist#435]
《概要》[RECORD]タブから既存のタスクIDを読み込んだ際、新たな
[WORKFLOW]を作成するにはブラウザをリロードする他方法がない。

《解決案》
・Wordなど一般的な事務ソフトのように、Save-Load機能を組み込む
・[WORKFLOW]に一括クリア(新規作成)ボタンを設置する。
・既存WORKFLOW IDを選択している場合は、上書きに注意させるなど、説明の
記載やアラートを追加する。

《仕様確認》[RUN ALL]を選択すると新規IDとして登録される

**Comment by ReiHashimoto** [comment]
resolved in ver1.1.0
