### ISSUE TITLE
WORKFLOW内のAlgorithmブロックが ドラッグに追従してしまう (oist_0214_7)

### ISSUE THREAD

**Issue by itutu-tienday** [oist/optinist#438]
Algorithmブロック内の[OUTPUT]ボタンをクリックした後に表示されるモーダル内において、チャートをドラッグすると、WORKFLOW内のAlgorithmブロックも追従して動いてしまいます。
解析結果には影響はないのですが、Algorithmブロックが思わぬ場所に移動していたりするので、不便に感じました

![image](https://user-images.githubusercontent.com/122338895/227176845-39a90501-0b63-46aa-b1fe-68308d0722ff.png)

- 事象発生箇所（モーダルのダイアログ・ツールチップが表示される箇所全般）
  - OUTPUTダイアログ
  - SELECT DATAダイアログ
  - エラーログ ダイアログ
  - etc.

**Comment by Reactplus-Hao** [comment]
Trong modal được hiển thị sau khi click vào button [OUTPUT] trong block Algorithm, 
thì khi drag chat thì block Algorithm trong WORKFLOW cũng bị di chuyển theo.
Phần bug này không ảnh hưởng đến kết quả phân tích, nhưng việc cho di chuyển block Algorithm đến chỗ không mong muốn gây bất tiện.

=> Nên KH nhờ bên mình est trước xem tốn bn effort để fix lỗi này. 
Sau đó họ sẽ điều chỉnh độ ưu tiên của task xem có cần xử lý luôn không.

※Nội dung note trên ảnh đính kèm: Sau khi di chuyể drag trong chat, và sau đó back lại WORKFLOW thì block cũng bị drag theo và bị di chuyển đến chỗ khác

**Comment by Reactplus-Hao** [comment]
Thông tin bổ sung: 
- Chỗ xảy ra issue này（Tất cả những chỗ hiển thị dialog modal・tooltip）
・Dialog OUTPUT
・Dialog SELECT DATA
・Dialog Log error
etc.

**Comment by Reactplus-Hao** [comment]
@itutu-tienday 
このチケットの事象発生箇所はエラーログ ダイアログとツールチップが表示される箇所を含めていますが、
弊社の方でこの２つの箇所を表示する方法が分かりませんので、
どうすればこの２つの箇所（エラーログ ダイアログとツールチップ）を表示させるか、教えて頂けますでしょうか。

**Comment by itutu-tienday** [comment]
@Reactplus-Hao 
エラーダイアログ（ツールチップ）は、添付イメージのものです。
※添付イメージのように、簡易にエラーを再現可能です。

![wf-ss](https://user-images.githubusercontent.com/122338895/230534123-83137210-958d-44eb-a002-a681d4ceb22b.png)

> 弊社の方でこの２つの箇所を表示する方法が分かりませんので、

当方で現在認識しているエラーの表示形式は、上記の1種類になります。

**Comment by Reactplus-Hao** [comment]
Về phần dialog Error log (Chính là tooltip) thì như ảnh đính kèm dưới đây
※Bên mình có thể dễ dàng tái hiện error như ảnh đính kèm (Ở ảnh này là lỗi đang không kết nối pipeline)

![Image](https://user-images.githubusercontent.com/87292605/230536128-cb9a1ad6-db18-4dfb-80ab-1ac6daf7feea.png)


----> KH đang hiểu là hiện tại format hiển thị lỗi chỉ có 1 loại như trên thôi ạ

**Comment by Reactplus-Hao** [comment]
@itutu-tienday 
#438について、全ての対象箇所に対して修正とテスト実施しました。
テスト実施結果は下記のファイルに記入し、動作のデモ動画は下記のフォルダに格納いたしました。
・**実施結果ファイル**：https://docs.google.com/spreadsheets/d/1yAeSzsBtXc6YW0si-7OIk9emkZJq59isnjrzEi0UPSQ/edit#gid=0
・**動作のデモ動画**：https://drive.google.com/drive/u/0/folders/1vycRQCPVGSiJFICFDFiPmObYo657clvW
お手数ですが、ご確認お願い致します。

**Comment by Reactplus-Hao** [comment]
@itutu-tienday 
このチケットの原因と内容内容について、下記の通りとなります。

- **原因**：
既存のソースコードでは、ポップアップのコンポーネントがReactFlowライブラリに存在しているためです。
- **対応内容**：
     ・ポップアップのコンポーネント（下記の３つの部分）をReactFlowライブラリの外に移動して、関連の関数を修正しました。
　　　　・AlgorithmOutputDialog, FileSelectDialog
　　　　・エラーログのダイアログについて、命名されていないため、下記の画像のソースコードをそのままコピーして、ReactFlowライブラリの外に移動しました。
<img width="491" alt="Screen Shot 2023-04-10 at 16 52 57" src="https://user-images.githubusercontent.com/87292605/230878922-92f1f68d-46e0-4c44-a52d-2de5598f9155.png">


- **備考**：詳細までレビューしたい時に、再度develop-mainブランチへ他のPRを作成することで、下記の画像のファイルの位置と詳細修正内容を確認できると思います。
<img width="972" alt="Screen Shot 2023-04-10 at 16 53 59" src="https://user-images.githubusercontent.com/87292605/230879435-b243bc4f-55e4-45f1-b09f-57435a6304f6.png">
