### ISSUE TITLE
[BE]動作保証されたモジュールのバージョンを指定する

### ISSUE THREAD

**Issue by emuemuJP** [oist/optinist#440]
- 対象機能
  - base (requirements)
  - nwb
  - caiman
  - suite2p
  - lccd

----
**以下の方針でモジュールバージョンを整理**

-  (2023/4/13) 版

- バージョン指定方針
  - 基本 (requirements)
    - アプリケーションの主要モジュールは、バージョンを指定する。（fastapi, nwb, ..）
    - バージョン指定は、基本的には 末尾ワイルドカード（*）の形式。
    - ユーティリティ系モジュールは、バージョン指定は省略可とする。
  - 個別アルゴリズムのモジュール
    - 個別アルゴリズムのモジュールは、バージョンを固定する。（caiman, suite2p, ..）
    - 個別アルゴリズムでは、 ユーティリティ系モジュールも、バージョン指定する。（末尾ワイルドカード形式）

- 注記
  - 現時点（2023/4）では、各モジュールは、基本的には 2022年後半頃のものを選択。
  - caimanは、OS環境間で インストール可能バージョンに差異があるため、バージョンを範囲指定している。
  - またOS環境間で、必ずしもモジュールバージョンを統一できないケースはあるため、モジュールバージョンを更新する際は、各対象OS環境についての動作確認が必要。

- 懸念点
  - バージョン指定ルールがやや細かくはないか。

**Comment by itutu-tienday** [comment]
モジュールバージョンを更新。 以下のテストケースを実施。

- 対象環境
  - Windows (11)
  - WSL (Ubuntu 22)
  - Linux (Ubuntu 22)
  - Mac (13, Intel)

- テストケース
  - 以下のworkflowを実施
  - ![スクリーンショット 2023-04-12 082736](https://user-images.githubusercontent.com/122338895/231645908-e12b3406-7d08-4ed4-b565-bddddfc00b57.png)

- テスト結果
  - Windows, Linux, Mac … OK
  - WSL … OKだが、OSへ幾つかライブラリをインストール（apt install）する必要があった。
    - 参考
      - https://qiita.com/momomo_rimoto/items/83917d3f9f5dd35457e1
      - https://omohikane.com/python3_open_cv_libsm/
