### ISSUE TITLE
optinist環境構築手順（開発者向け）修正版レビュー

### ISSUE THREAD

**Issue by itutu-tienday** [oist/optinist#442]
optinistの環境構築手順（開発者向け）修正版のレビューを行う。

- 対象ドキュメント
  - (Windows for Developer) https://github.com/oist/optinist/blob/develop-main/docs/installation/windows_for_developer.md
  - (Mac for Developer) https://github.com/oist/optinist/blob/develop-main/docs/installation/mac_for_developer.md

- ドキュメントの修正ポイント
  - Windows, Mac 上の環境において、snakamake の use_conda に問題が生じやすいことから、snakamake の use_conda を利用しない環境構築手順（暫定バージョン）を準備している。

- タスク
  - Windows, Mac （for Developer）の環境構築手順で、「caiman + suite2p」を利用するWorkflowが正常動作するかを確認する。
  - 何らか懸念事項があれば、レポートする。

- 期限
  - 2023/4初旬

- 関連
  - #402

**Comment by Reactplus-Hao** [comment]
**Tiến hành review bản chỉnh sửa Trình tự build môi trường optinist (Dành cho developer)**
- Document cần review:
    ・(Windows for Developer) https://github.com/oist/optinist/blob/develop-main/docs/installation/windows_for_developer.md
　・(Mac for Developer) https://github.com/oist/optinist/blob/develop-main/docs/installation/mac_for_developer.md

- Điểm chỉnh sửa trong document:
Do trong môi trường trênWindows, Mac dễ xảy ra lỗi về use_conda trong snakemake, nên họ đã chuẩn bị trình tự build môi trường mà không sử dụng use_conda trong snakemake 
(Trình tự này đang ở version giả định thôi, và họ cần nhờ mình check hoạt động xem có vấn đề gì k. Nếu k có vấn đề gì thì mới dùng trình tự này)

- Task bên mình cần làm:
     ・Check với trình tự build môi trường trên Windows, Mac （for Developer）xem Workflow mà sử dụng 「caiman + suite2p」có hoạt động đúng hay không?
     ・Nếu có điểm bất thường hay phần nào bên mình để ý thì report cho họ.

- Deadline: Đầu tháng 4 (1/4~10/4)

- Ticket liên quan:
https://github.com/oist/optinist/issues/402

**Comment by Reactplus-Hao** [comment]
@itutu-tienday 

> 対象ドキュメント
(Windows for Developer) https://github.com/oist/optinist/blob/develop-main/docs/installation/windows_for_developer.md
(Mac for Developer) https://github.com/oist/optinist/blob/develop-main/docs/installation/mac_for_developer.md

- 上記のの環境構築手順で、「caiman + suite2p」を利用するWorkflowが正常動作していることを確認できました。
- 懸念事項について、環境構築手順のステップを短縮するために、各環境ファイルを１つのファイルに事前にマージしてリポジトリに保存することを考えております。
その時、conda-mergeコマンドを使用しているステップとInstall requirementsステップが不要になります。
ご検討、よろしくお願いいたします。

**Comment by itutu-tienday** [comment]
確認ありがとうございました。

なお以下の関連issueでも、環境構築に関する課題への検証を継続しています。
- #446
※現時点では、上記issue内での対応により、当issueの対応（暫定）は不要となることが見込まれる。
