### ISSUE TITLE
Snakemakeにおけるuse_condaの課題

### ISSUE THREAD

**Issue by itutu-tienday** [oist/optinist#446]
Snakemakeのuse_conda（新しいアルゴリズムを利用する際に、conda環境を自動生成する機能）において、以下の様な課題が確認されている。

- conda create env に失敗する。
  - 停止し応答がなくなる （caimanなど）
- conda create env に成功はするが、非常に時間を要する。（1時間以上など）

上記について、use_conda を 安定稼働・性能向上 させるための、調査・検証を行う。

- 関連issue
  - #378 
  - #419 
  - #420
  - #422

**Comment by itutu-tienday** [comment]
（メモ）
snakemaker公式では、condaの代替にmambaの利用が推奨されていることから、mambaの利用を検証する。
https://snakemake.readthedocs.io/en/stable/getting_started/installation.html

**Comment by itutu-tienday** [comment]
現在までの、当方環境における、「snakemake + use_conda(mamba)」構成の動作確認状況を、以下記載。

| 環境 | 環境詳細 | snakemake + conda | snakemake + mamba |
| -- | -- | -- | -- |
| Docker | - | OK | (未確認) |
| Linux | Ubuntu 22, Virtualbox | NG (caiman の create envで停止) | NG （同左） |
| Windows | 11, Native | OK (conda.bat の @echo off が必要)  | (未確認) （mamba が 他の unix-like 環境と比較し、若干特殊？） |
| Windows | 11, WSL | NG (OKの場合もある？環境要因？) | OK (ただし、初回は長時間(2-3時間)の処理を要する) |
| Mac | 13 | NG (OKの場合もある？環境要因？) | OK |

- 解説
  - 前提として、mamba は、snakemakeやcaimanの導入ツールとして推奨されている。
  - mamba は Mac環境などでは、安定動作している様に見えている。
  - しかし conda, mamba によらず、「初回のcaimanのcreate env」で、失敗するケース（無限に待機する）が多い状況。
    - #419 の事象
  - mamba でも問題は発生している様であるため（Linux環境）、今少し要因調査や、複数環境での検証が必要と想定される。

**Comment by emuemuJP** [comment]
M2 Mac環境ではエラー発生してしまいました
<img width="1344" alt="スクリーンショット 2023-04-05 21 16 59" src="https://user-images.githubusercontent.com/49627335/230077883-9645d3f0-9623-483f-afc4-2645d305f400.png">

**Comment by itutu-tienday** [comment]
上記のログから、.snamake ディレクトリ配下のファイルへの、fastapiのリロードが発生していることが確認できる。
このリロードが動作に影響を与えている可能性があるため（不要な処理かつ負荷の高い処理）、不要なリロードを抑制する設定を検証する。

- 関連
  - #459

**Comment by ReiHashimoto** [comment]
- ARM(M1, M2)環境での実行関連
  - https://github.com/oist/optinist/pull/461#issuecomment-1501338545
  - https://github.com/oist/optinist/pull/461#issuecomment-1501395395
  - https://github.com/oist/optinist/pull/461#issuecomment-1501466647

**Comment by ReiHashimoto** [comment]
mambaで実行
- channel_priorityはrestrict, flexibleそれぞれ実行

いずれもcondaの場合と同様のエラーでfail
--> インストールするcondaやmambaをintel版にして、rosetta経由での実行で試してみます

## 実行コマンドログ
[20230410_mamba_restrict_and_flexible.txt](https://github.com/oist/optinist/files/11188543/20230410_mamba_restrict_and_flexible.txt)

**Comment by ReiHashimoto** [comment]
@itutu-tienday 
armアーキテクチャのMac上にIntel版のanacondaを入れることで動作することが確認できました。
mambaではなく、通常のanacondaを使用しています。

![127 0 0 1_8000_](https://user-images.githubusercontent.com/42664619/230857152-4bf8d236-8630-4845-9769-0602e260d133.png)

[20230410_conda_intel_on_m2.txt](https://github.com/oist/optinist/files/11188832/20230410_conda_intel_on_m2.txt)

**Comment by emuemuJP** [comment]
mambaで依然としてエラーが発生
GPT-4による推測は以下
```
原因と対処法は以下のとおりです。

不足しているパッケージやバージョンの競合:

suite2p_env.yamlファイルを確認し、依存関係が正しく記述されていることを確認してください。
必要に応じて、パッケージのバージョンを更新またはダウングレードして競合を解決してください。
メモリ不足:

エラーメッセージのKilled: 9は、システムがプロセスをメモリ不足のために強制終了したことを示している場合があります。
他のメモリを消費しているアプリケーションを閉じてから、再度Conda環境の作成を試みてください。
必要に応じて、システムのメモリを増設することも検討してください。
パッケージのインストール時に一時ファイルの書き込みに問題がある場合:

ディスク容量が十分にあることを確認してください。不要なファイルやアプリケーションを削除してディスク容量を確保してください。
ディレクトリのパーミッションを確認し、必要に応じて書き込み許可を与えてください。
問題が解決しない場合は、エラーメッセージとともに適切なサポートフォーラムに質問してください。
```
<img width="1335" alt="スクリーンショット 2023-04-11 16 02 04" src="https://user-images.githubusercontent.com/49627335/231081698-bfedf15d-9e4f-4316-9875-8405b0816802.png">

**Comment by emuemuJP** [comment]
workflow全体とエラー発生までのログ
<img width="815" alt="スクリーンショット 2023-04-11 16 16 58" src="https://user-images.githubusercontent.com/49627335/231084876-40ad457f-ca3e-440c-b697-1e1cbaabcecc.png">
<img width="1335" alt="スクリーンショット 2023-04-11 16 16 48" src="https://user-images.githubusercontent.com/49627335/231084922-826fbfed-53c5-463f-93cb-4f0a7aa65b17.png">
<img width="1335" alt="スクリーンショット 2023-04-11 16 16 36" src="https://user-images.githubusercontent.com/49627335/231084943-96b4c90b-8d46-410d-a5d8-1b6359708bbf.png">

**Comment by emuemuJP** [comment]
mambaで入れてない環境もエラーが発生するようになる
<img width="1332" alt="スクリーンショット 2023-04-11 16 20 41" src="https://user-images.githubusercontent.com/49627335/231086090-c1692e33-f7e6-4266-a0f5-11ea7dd9ad5d.png">
<img width="1332" alt="スクリーンショット 2023-04-11 16 20 51" src="https://user-images.githubusercontent.com/49627335/231086102-595e4ca5-0ea8-491a-aca4-8dd31d67d5ee.png">

**Comment by emuemuJP** [comment]
現状mambaを使うと元々使用していた環境に破壊的な影響が出るかもしれないのでしっかり手順を構築出来ないと危険。
https://github.com/oist/optinist/issues/446#issuecomment-1501535886
こちらであるようにarmのmambaとintelのcondaが混合したことによるエラーな気がしました
手順によりダウンロードされたmambaのinstall shell
Mambaforge-Darwin-arm64.sh

**Comment by itutu-tienday** [comment]
@emuemuJP 
> こちらであるようにarmのmambaとintelのcondaが混合したことによるエラーな気がしました
なるほど…その可能性はあるようですね。確認ありがとうございます。

またこれは改善効果は得られないかもしれませんが、
上記のログ中、` conda config --set channel_priority strict` の実施推奨のログが出ていますが、そちらを設定による変化も、確認できればと思います。

**Comment by ReiHashimoto** [comment]
@itutu-tienday @emuemuJP 

私の方でARM(M2)Macでmamba(Intel版)での環境構築の確認を行いました。
結論としては、Intel版を入れれば問題なさそうです。
昨日私がmambaで検証してfailした際はMambaforge-Darwin-arm64.shでarm版を入れていたので、
https://github.com/oist/optinist/issues/446#issuecomment-1502826201
とfailする条件も合致すると思われます。

従って、以下のようなパターンでドキュメントの修正が必要かと思われます。
(condaのパターンも含め)

- Macのアーキテクチャによって記述を分岐させる
- インストールコマンドにunameなどによる判定の分岐を入れる

## Result

[issue446_mamba_intel_on_m2.log](https://github.com/oist/optinist/files/11198052/issue446_mamba_intel_on_m2.log)

![Screenshot 2023-04-11 at 16 54 11](https://user-images.githubusercontent.com/42664619/231093893-e85bc414-4270-48ce-b66f-aeae2cb250d3.png)

## Install

手順書に記載のあった以下のコマンドでのインストールではなく、
```
curl -L -O "https://github.com/conda-forge/miniforge/releases/latest/download/Mambaforge-$(uname)-$(uname -m).sh"
bash Mambaforge-$(uname)-$(uname -m).sh
```

https://github.com/conda-forge/miniforge#mambaforge
からIntel版のファイルをダウンロード
![Screenshot 2023-04-11 at 16 50 34](https://user-images.githubusercontent.com/42664619/231093247-a0b26801-6eff-48f3-bf10-1eb5b2e28710.png)

ユーザーディレクトリ直下にダウンロードしたファイルを配置していたので、以下のコマンドでインストール実行
```
bash Mambaforge-MacOSX-x86_64.sh
```

以降はドキュメント通りの操作です。

**Comment by ReiHashimoto** [comment]
FYI

M2Macの場合の`uname`出力
```
$ uname
Darwin
$ uname -m
arm64
```

**Comment by itutu-tienday** [comment]
※当件について、以下現状の対応方針メモ。

1.  v0.3.0時点では、conda を利用したインストール手順で整理する。
    - 検証者の環境では、conda での create env は、現状安定している模様。（1環境の構築に時間は要する（30分前後程度））
2. 今後、チーム内で mamba の安定稼働が確認されたのち、mamba のインストール手順も追加。
3. また、機能開発（任意のconda環境を選択できる機能）も見据える。
