### ISSUE TITLE
相対パスの修正

### ISSUE THREAD

**Issue by emuemuJP** [oist/optinist#460]
以下パスの指定に問題がある可能性
https://github.com/oist/optinist/blob/main/optinist/wrappers/lccd_wrapper/lccd_python/blob_detector.py#L9-L10

**Comment by itutu-tienday** [comment]
@emuemuJP 
当件について、再現確認を行ったところ、再現を確認できませんでした。（処理に成功する）
- 環境 … optinist pip module版、version.0.2.1、Widows 11 Native上

上記につき、再現手順を確認したいと思います。

**Comment by ReiHashimoto** [comment]
私の方でも再現せずでした。

### 環境
- optinist: pip版, 0.2.2
- MacOS, 13.3.1, arm64(m2)
- anaconda, 23.1.0

### 検証ワークフロー
![Screenshot 2023-04-19 at 9 28 30](https://user-images.githubusercontent.com/42664619/232935966-ab4e2764-4341-49f0-a321-8a29c51359d2.png)

### log
[pip_lccd.log](https://github.com/oist/optinist/files/11267380/pip_lccd.log)

**Comment by ShogoAkiyama** [comment]
こちらに関しては、動く/動かないにせよコードに相対パスが入ってる部分を直したいです。
https://github.com/oist/optinist/blob/main/optinist/wrappers/lccd_wrapper/lccd_python/blob_detector.py#L9-L10

相対パスがあると、呼び出し時にバグる可能性があります。

**Comment by itutu-tienday** [comment]
修正箇所は、以下、一定量がある模様。（wrapper配下が主）

> optinist/wrappers/__init__.py(1,1)  [UTF-8]: `from .`caiman_wrapper import caiman_wrapper_dict
> optinist/wrappers/__init__.py(2,1)  [UTF-8]: `from .`suite2p_wrapper import suite2p_wrapper_dict
> optinist/wrappers/__init__.py(3,3)  [UTF-8]: # `from .`dummy_wrapper import dummy_wrapper_dict
> optinist/wrappers/__init__.py(4,1)  [UTF-8]: `from .`optinist_wrapper import optinist_wrapper_dict
> optinist/wrappers/__init__.py(5,1)  [UTF-8]: `from .`lccd_wrapper import lccd_wrapper_dict
> optinist/wrappers/caiman_wrapper/__init__.py(1,1)  [UTF-8]: `from .`motion_correction import caiman_mc
> optinist/wrappers/caiman_wrapper/__init__.py(2,1)  [UTF-8]: `from .`cnmf import caiman_cnmf
> optinist/wrappers/dummy_wrapper/__init__.py(1,1)  [UTF-8]: `from .`dummy import *
> optinist/wrappers/lccd_wrapper/lccd_detection.py(8,5)  [UTF-8]:     `from .`lccd_python.lccd import LCCD
> optinist/wrappers/lccd_wrapper/__init__.py(1,1)  [UTF-8]: `from .`lccd_detection import lccd_detect
> optinist/wrappers/lccd_wrapper/lccd_python/blob_detector.py(9,1)  [UTF-8]: `from .` import oval_filter
> optinist/wrappers/lccd_wrapper/lccd_python/blob_detector.py(10,1)  [UTF-8]: `from .`utils import matlab_conv2
> optinist/wrappers/lccd_wrapper/lccd_python/lccd.py(7,1)  [UTF-8]: `from .`blob_detector import BlobDetector
> optinist/wrappers/lccd_wrapper/lccd_python/lccd.py(8,1)  [UTF-8]: `from .`roi_integration import RoiIntegration
> optinist/wrappers/lccd_wrapper/lccd_python/oval_filter.py(5,1)  [UTF-8]: `from .` import utils
> optinist/wrappers/lccd_wrapper/lccd_python/roi_integration.py(5,1)  [UTF-8]: `from .` import utils
> optinist/wrappers/optinist_wrapper/__init__.py(1,1)  [UTF-8]: `from .`basic_neural_analysis import basic_neural_analysis_wrapper_dict
> optinist/wrappers/optinist_wrapper/__init__.py(2,1)  [UTF-8]: `from .`dimension_reduction import dimension_reduction_wrapper_dict
> optinist/wrappers/optinist_wrapper/__init__.py(3,1)  [UTF-8]: `from .`neural_population_analysis import neural_population_analysis_wrapper_dict
> optinist/wrappers/optinist_wrapper/__init__.py(4,1)  [UTF-8]: `from .`neural_decoding import neural_decoding_wrapper_dict
> optinist/wrappers/optinist_wrapper/basic_neural_analysis/__init__.py(1,1)  [UTF-8]: `from .`eta import ETA
> optinist/wrappers/optinist_wrapper/basic_neural_analysis/__init__.py(2,3)  [UTF-8]: # `from .`cell_grouping import cell_grouping
> optinist/wrappers/optinist_wrapper/dimension_reduction/__init__.py(1,1)  [UTF-8]: `from .`cca import CCA
> optinist/wrappers/optinist_wrapper/dimension_reduction/__init__.py(2,1)  [UTF-8]: `from .`pca import PCA
> optinist/wrappers/optinist_wrapper/dimension_reduction/__init__.py(3,1)  [UTF-8]: `from .`tsne import TSNE
> optinist/wrappers/optinist_wrapper/neural_decoding/__init__.py(1,1)  [UTF-8]: `from .`glm import GLM
> optinist/wrappers/optinist_wrapper/neural_decoding/__init__.py(2,1)  [UTF-8]: `from .`lda import LDA
> optinist/wrappers/optinist_wrapper/neural_decoding/__init__.py(3,1)  [UTF-8]: `from .`svm import SVM
> optinist/wrappers/optinist_wrapper/neural_population_analysis/__init__.py(1,1)  [UTF-8]: `from .`correlation import correlation
> optinist/wrappers/optinist_wrapper/neural_population_analysis/__init__.py(2,1)  [UTF-8]: `from .`cross_correlation import cross_correlation
> optinist/wrappers/optinist_wrapper/neural_population_analysis/__init__.py(3,1)  [UTF-8]: `from .`granger import Granger
> optinist/wrappers/suite2p_wrapper/__init__.py(1,1)  [UTF-8]: `from .`file_convert import suite2p_file_convert
> optinist/wrappers/suite2p_wrapper/__init__.py(2,1)  [UTF-8]: `from .`registration import suite2p_registration
> optinist/wrappers/suite2p_wrapper/__init__.py(3,1)  [UTF-8]: `from .`roi import suite2p_roi
> optinist/wrappers/suite2p_wrapper/__init__.py(4,1)  [UTF-8]: `from .`spike_deconv import suite2p_spike_deconv
> optinist/wrappers/suite2p_wrapper/edit_roi/add_roi.py(4,1)  [UTF-8]: `from .`utils import get_im, get_stat0_add_roi, masks_and_traces, save_json_data
> optinist/wrappers/suite2p_wrapper/edit_roi/delete_roi.py(3,1)  [UTF-8]: `from .`utils import get_im, save_json_data
> optinist/wrappers/suite2p_wrapper/edit_roi/merge_roi.py(3,1)  [UTF-8]: `from .`utils import get_im, save_json_data
> optinist/wrappers/suite2p_wrapper/edit_roi/__init__.py(1,1)  [UTF-8]: `from .`add_roi import execute_add_ROI
> optinist/wrappers/suite2p_wrapper/edit_roi/__init__.py(2,1)  [UTF-8]: `from .`merge_roi import execute_merge_roi
> optinist/wrappers/suite2p_wrapper/edit_roi/__init__.py(3,1)  [UTF-8]: `from .`delete_roi import excute_delete_roi
>
