### ISSUE TITLE
Record画面での処理エラーの詳細表示

### ISSUE THREAD

**Issue by itutu-tienday** [oist/optinist#492]
現在、Records画面では、処理結果のエラーの詳細を確認することができない。
※Workflow画面上では、各ノードのエラーアイコンから、エラー詳細を確認可能。
※Recordsのデータ保存時（experiments.yaml）、エラー詳細情報が記録されていないため。

上記に対して、Record画面にて、処理エラーの詳細を確認できるようにする。

**Comment by ReiHashimoto** [comment]
experiments.yaml に保存する情報に、各ノード、及びWF全体の

1. 処理開始時間
2. 処理完了時間

を追加する
各処理の所要時間を、後に確認できるようにするため

※現在は、おそらく処理開始時間のみ

https://github.com/oist/optinist/blob/35209ff03710b1d5b02d3897034e55b163588b21/optinist/routers/run.py#L13-L16

https://github.com/oist/optinist/blob/35209ff03710b1d5b02d3897034e55b163588b21/optinist/api/workflow/workflow_runner.py#L18-L27

https://github.com/oist/optinist/blob/35209ff03710b1d5b02d3897034e55b163588b21/optinist/api/experiment/experiment_writer.py#L30-L39

https://github.com/oist/optinist/blob/35209ff03710b1d5b02d3897034e55b163588b21/optinist/api/experiment/experiment_writer.py#L49-L57

**Comment by ReiHashimoto** [comment]
resolved in ver1.1.0
