### ISSUE TITLE
ユニットテスト更新（BE）

### ISSUE THREAD

**Issue by itutu-tienday** [oist/optinist#507]
BackEndのユニットテストについて、不足のあるテストケースの追加等、改善を行う。

- 関連
  - #404 
    - https://github.com/oist/optinist/issues/404#issuecomment-1535621859

**Comment by Reactplus-Hao** [comment]
Về phần unit test của Backend, tiến hành thêm test code và cải thiện những chỗ còn thiếu.
- Các phần chưa có test:
    - caiman_wrapper
    - lccd_wrapper
    - optinist_wrapper
    - dummy_wrapper
    - edit ROI
    - optinist/api/dataclass
    - optinist/api/nwb
