### ISSUE TITLE
parameterが手入力値を受け入れない

### ISSUE THREAD

**Issue by emuemuJP** [oist/optinist#509]
Mac環境と一部Docker環境では発生しておらず、特定のDocker versionでのみ発生している模様

<img width="682" alt="スクリーンショット 2023-06-16 13 06 04" src="https://github.com/oist/optinist/assets/49627335/a6d7f9b5-fb61-4c25-9c6a-39714ba85cce">

**Comment by ReiHashimoto** [comment]
Close because we couldn't reproduce it.
