### ISSUE TITLE
特定のパラメータを変更するとエラーになる

### ISSUE THREAD

**Issue by emuemuJP** [oist/optinist#510]
suite2P registration の　block_size と caiman_cnmf の gSig （どちらも２つの要素を持つ array) を変更するとnot supported between instances of 'str' and 'int'と言うエラーが出て受け付けない
<img width="1360" alt="スクリーンショット 2023-06-16 13 03 59" src="https://github.com/oist/optinist/assets/49627335/21126f6d-d4dd-41a0-9857-5f13f6dd62b8">

**Comment by ReiHashimoto** [comment]
おそらくデータ型が変わってしまうのが原因

- いずれもバックエンドではlistとして扱いたいパラメータ
    - caiman_cnmf.yaml
      ```
      gSig: [4, 4]
      ```      
    - suite2p_registration.yaml
      ```
      block_size: [128, 128]
      ```
      
- フロントエンドのinput formで変更した際にこれらがおそらく`"256, 256"`というstringに変わっているので、frontendかbackendのどちらかでlistに変換する必要がある。
  - できればフロントエンド側
    - onChangeで元のデータ型に変換させる、など?

**Comment by reactplus-thom** [comment]
Khi thay đổi gSig của block_size và caiman_cnmf của suite2P registration (cả 2 đều là array với 2 element) thì bị lỗi not supported between instances of 'str' and 'int' và không chấp nhận.

Nguyên nhân có thể là do kiểu dữ liệu đã bị thay đổi.
- Cái nào dưới đây cũng là parameter mà phía BE muốn coi là list

caiman_cnmf.yaml
gSig: [4, 4]
suite2p_registration.yaml
block_size: [128, 128]

- Có lẽ những cái này bị chuyển thành string "256, 256" khi thay đổi bằng input form phía FE, vì thế cần 1 trong 2 phía FE hoặc BE connvert nó thành list.
Nếu được thì phía FE hãy convert thành kiểu dữ liệu ban đầu khi onChange chẳng hạn.
