### ISSUE TITLE
ワークフロー処理の中断APIの実装

### ISSUE THREAD

**Issue by itutu-tienday** [oist/optinist#511]
現行optinistのWorkflowのRUN Cancel処理は、FrontEndで完結した動作（BackEndへ終了通知が投げられていない）となっている。
シングルユーザー利用であればあまり問題とならないが、マルチユーザーで利用する場合や、関連issueの内容から、ワークフロー処理の中断処理が必要となることが想定される。

上記、ワークフロー処理の中断API の実装を検討・実施する。

- 対応内容
  - Workflow RUN Cancel API の作成
  - Workflow RUN Cancel 処理の実装（Snakemake）
  - FrontEnd調整（RUN Cancel API の呼び出し）

- 関連
  - https://github.com/arayabrain/MRIAnalysisStudioforMouse/issues/68
  - https://github.com/arayabrain/MRIAnalysisStudioforMouse/issues/58
  - https://github.com/arayabrain/MRIAnalysisStudioforMouse/issues/64

**Comment by itutu-tienday** [comment]
（調査メモ）

- snakemake公式FAQ
  - https://snakemake.readthedocs.io/en/stable/project_info/faq.html#how-do-i-exit-a-running-snakemake-workflow
    > How do I exit a running Snakemake workflow?
    > `killall -TERM snakemake`

上記はpythonモジュールではなく、snakemake単体での解説だが、同様であれば、実行時のpidを保持することで、kill操作が可能か。

**Comment by ReiHashimoto** [comment]
resolved in ver1.0.0
