### ISSUE TITLE
[No.41]分割tiff fileの並び順

### ISSUE THREAD

**Issue by emuemuJP** [oist/optinist#514]
フォルダから分割tiff fileを読み込んだ際にGUIで確認できない。

**Comment by ReiHashimoto** [comment]
要望管理表No.41

分割TIFFファイルをINPUTディレクトリに入れた際に、ファイル名でソートされずにファイル生成日時順にソートされてしまう。

ただし、ファイルの処理は名前順に行われているためGUIのみの問題。

**Comment by emuemuJP** [comment]
Sample dataはこちらです
https://dataportal.brainminds.jp/caimaging-okano-1

**Comment by reactplus-thom** [comment]
Không thể check bằng GUI khi upload từ folder đối với file tiff phân tách .
Khi upload file tiff phân tách vào thư mục INPUT thì đang ko sort theo file name mà lại sort theo ngày giờ generate file.
Tuy nhiên, xử lý file thì vẫn đang sort theo file name vì thế đây là vấn đề riêng phía GUI.

Sample dat (file tiff):
https://dataportal.brainminds.jp/caimaging-okano-1

**Comment by ReiHashimoto** [comment]
@reactplus-thom 

> ファイルの処理は名前順に行われているためGUIのみの問題

と記載しましたが、Backend側も念のため期待通りのコードになっているか調査いただけますか？

**Comment by reactplus-thom** [comment]
@emuemuJP 
すみません、本事象はどこの画面で発生しているのか教えていただけないでしょうか。
また事象発生時のキャプチャーがある場合ご共有頂ければ助かります。

**Comment by ReiHashimoto** [comment]
@reactplus-thom 
※ユーザーにも再度確認を取ります。暫定でコメントします。


スクリーンショットを添付します。
Imageのdata nodeで複数のファイルを選択した際に、選択されたファイルが表示されます。
AsIs: 選択した順でソート
ToBe: ファイル名でソート(asc)
です。

![Screenshot 2023-06-28 at 20 59 36](https://github.com/oist/optinist/assets/42664619/c85a2274-a1c3-4a3d-ac4e-393dade4cebb)

理由ですが、複数のファイルを選択するケースは、
本来連続した動画だが、容量上の問題でファイルを分割している場合です。
つまり、解析の際には連続した1動画として扱いたく、バックエンドではファイル名で昇順に読み込むものとしています（この想定が正しいかもバックエンドの処理を確認したい、というのが追加していた依頼です）。

バックエンドでの処理順と、フロントエンドで表示されている順序が一致していないことで、ユーザーに誤解を与える恐れがあるため、これらを一致させる対応を行います。

**Comment by reactplus-thom** [comment]
Lỗi xảy ra khi chọn folder bằng data node của Image.

Cách tái hiện
-------
1. Tạo và lưu trực tiếp folder file tiff vào OPTINIST_DIR/input 
(do phía GUI không có chức năng upload folder nên sẽ phải lưu trực tiếp vào folder) 
2. Click vào SELECT IMAGE của Image data node
3. Tên của folder đã thêm vào OPTINIST_DIR/input sẽ được hiển thị => click vào tên folder sẽ để hiển thị các file bên trong

Lúc này sẽ thấy file hiển thị không theo quy tắc nào cả như ảnh dưới đây (xem ảnh ở comment bên trên)
(không phải theo generate time, update time hay tên file hay gì cả => ko rõ là  theo thứ tự nào)

ToDo
--------
- AsIs: Không rõ thứ tự hiển thị của file là gì

- ToBe: Sort theo tên file (asc)

- Về cột Select File
+ Trường hợp tick vào từng file một: tên file hiển thị theo thứ tự được tick (cái này OK rồi)
+ Trường hợp chọn folder: đang thấy là file trong folder hiển thị ở Select File theo thứ tự file name tăng dần (asc) giống như khi hiển thị

Bối cảnh của việc chỉnh sửa này
----------
Khi chọn nhiều file, đáng lẽ ra video phải đọc liên tục nhưng đang có những trường hợp file bị split do vấn đề vượt dung lượng.
Tức là, để đọc được thành 1 video liên tục thì phía backend phải đọc theo thứ tự tên file sắp xếp asc (=> chính vì thế muốn nhờ phía BE confirm xem xử lý phía BE chỗ này có đang đúng hay không).

Hiện tại, thứ tự xử lý phía BE và thứ tự hiển thị phía FE đang không khớp nhau, khiến cho user hiểu nhầm, vì thế mục đích cuối cùng là sửa để cho 2 phía match nhau.

**Comment by ReiHashimoto** [comment]
上記PRで解消されていることを確認


- ファイルツリーの表示順が名前昇順になっている
  - files APIレスポンスのデータを以下の処理でリスト化しているので、この表示順がバックエンドに依存(今回のPRで修正)
  - https://github.com/oist/optinist/blob/d2c708d521604d63eecff6874388e439f00d31ac/frontend/src/store/slice/FilesTree/FilesTreeUtils.ts#L4-L19
- フォルダを選択した際は、保持しているリストの順序そのままでフォルダ内のファイルが選択済ファイル欄に追加される
  - したがって、ファイルツリーの表示順がsortされていればこちらもsortされる
- 個別にフォルダ内のファイルを選択した際には選択順で選択済ファイル欄に表示される
  - https://github.com/oist/optinist/blob/d2c708d521604d63eecff6874388e439f00d31ac/frontend/src/components/common/FileSelectDialog.tsx#L121-L132
  - https://github.com/oist/optinist/blob/d2c708d521604d63eecff6874388e439f00d31ac/frontend/src/components/common/FileSelectDialog.tsx#L87
- 選択済ファイル欄に表示されている順の配列でAPIリクエストボディに渡されるため、バックエンドでもその順序で処理ができる

suite2p_file_convertで選択順序を変えたパターンで以下を確認済
- ソース内での配列処理の順序が選択順序になっていること
- 結果のmeanImgが異なること

**Comment by emuemuJP** [comment]
@ReiHashimoto こちらで認識・動作相違ないです
