### ISSUE TITLE
[No.47]Plot での表示cellID を内部処理のcellIDと合わせる

### ISSUE THREAD

**Issue by emuemuJP** [oist/optinist#517]
現在NWBに書き込まれるcellIDは0はじまりだが、フロントエンドで表示されるcellIDは１はじまりになっており、混乱を生じているため０始まりに統一する

**Comment by ReiHashimoto** [comment]
- plot表示のIDが1始まりである理由はない
- 0をNaNにする処理があるため、0始まりにするとまずいので1からにした程度
    ```
    im = np.stack(arrays)
    im[im == 0] = np.nan
    ```

### 主な修正箇所
- https://github.com/oist/optinist/tree/main/optinist/api/dataclass/timeseries.py#L33-L37
- suite2p
    - https://github.com/oist/optinist/tree/main/optinist/wrappers/suite2p_wrapper/roi.py#LL51C1-L51C1
- caiman_cnmf
    - https://github.com/oist/optinist/tree/main/optinist/wrappers/caiman_wrapper/cnmf.py#L38
- lccd
    - https://github.com/oist/optinist/tree/main/optinist/wrappers/lccd_wrapper/lccd_detection.py#L28-L33
- frontで関連するかもしれない部分
    - https://github.com/oist/optinist/tree/main/frontend/src/store/slice/DisplayData/DisplayDataSlice.ts#L284-L317

### 修正方針
- ROIでない場所をNaN, roiは0始まりにする
    ```
    im[im == 0] = np.nan
    im -= 1
    ```
    のようにすればOK

**Comment by itutu-tienday** [comment]
Note)
今回の修正により、過去のROIデータとの互換性は失われる形になる。
