### ISSUE TITLE
[No.26]WORKFLOW のプルダウンメニューの順序の整理

### ISSUE THREAD

**Issue by emuemuJP** [oist/optinist#520]
新しく追加した細胞抽出アルゴリズム(lccd)がoptinistの下にあるため並び順を変更する
<img width="164" alt="スクリーンショット 2023-06-23 16 15 25" src="https://github.com/oist/optinist/assets/49627335/21203fe7-325c-4c75-b809-d2dcb0c5d969">

### 想定対応内容

- 並び順を caiman, suite2p, lccd, optinist の順とする
- wrapper モジュールのwrapper_dict.update順序の並び替えによる対応を想定

**Comment by ReiHashimoto** [comment]
開発要望管理表No.26

- caiman, suite2p, lccd, optinistの順

**Comment by itutu-tienday** [comment]
- PR
  - https://github.com/arayabrain/barebone-studio/pull/44
