### ISSUE TITLE
開発者・コントリビューター向けドキュメントメンテナンス

### ISSUE THREAD

**Issue by itutu-tienday** [oist/optinist#522]
以下のようなドキュメントの作成・メンテナンスを想定
※FE、BEの両方を対象

- システム仕様
  - ディレクトリ構成、ソース構成、etc
  - 利用ソフトウェア・ミドルウェア構成（バージョン、etc）

- 開発ルール
  - 開発規約（コーディングルール、UIルール、非機能、テスト、etc）
  - Git運用ルール

**Comment by ReiHashimoto** [comment]
Resolved in ver1.1.0
