### ISSUE TITLE
FrontEndビルドの性能改善

### ISSUE THREAD

**Issue by itutu-tienday** [oist/optinist#524]
optinistのfrontendのビルド（yarn start, yarn build）において、マシン性能にもよるが、数分～5分程度 （Docker環境では10分以上）要するケースがある。

要因の調査と、改善を実施する。

- 対象環境
  - [x] 1. MRIAnalysisStudio （※対応必須ではないが、検証目的で対応）
      - https://github.com/arayabrain/MRIAnalysisStudioforMouse/issues
  - [x] 2. OptiNiSt
      - https://github.com/oist/optinist

**Comment by reactplus-thom** [comment]
Khi build frontend của optinist (bằngyarn start, yarn build), thời gian build cũng sẽ tùy thuộc vào máy nhưng thường là mất khoảng 5 phút (trên docker thậm chí còn mất hơn 10p).

Hãy điều tra nguyên nhân của việc này và cải thiện.

Môi trường:
1. MRIAnalysisStudio （※đối ứng để phục vụ cho việc test)
https://github.com/arayabrain/MRIAnalysisStudioforMouse/issues

2. OptiNiSt
https://github.com/oist/optinist

**Comment by itutu-tienday** [comment]
@reactplus-thom 
PRを発行いただいているようですが、調査結果はissueを追記をお願いします。

また以下、コメントへ回答します。

> また、下記2点補足です。
> ・対応内容として、ビルドの方法を修正していますが、
> 　現状のFEビルドに時間がかかる原因の一部は、ソースのファイル数とソースがtypescriptであることにもあります。
> 　※compile実行前にvalidate type, eslint formatを実行しますので。

了解しました。
なお、思い当たる改善対策は、現状は他にない状況でしょうか。

> ・Optinistの方は、現状FEはdockerの環境を使っていないですので、調査などはしていない状態です。
> →チケット内容確認時に連絡できておらずすみません。
> また、Optinistも対応する必要の場合、Dockerを構築して対応いたしますが、ご連絡お願い致します。

Docker環境に限定せず、build性能の改善が目的になります。
以下をご確認・共有いただければと思います。
- そちらの動作確認環境（OSなど）、事象再現状況（そちらでの処理所要時間）、など

**Comment by reactplus-thom** [comment]
- Chi tiết về kết quả điều tra (đã xác nhận trên môi trường nào, OS nào, kết quả chạy thực tế đang như thế nào)
- Tất cả các nguyên nhân có thể gây ảnh hưởng mà mình đang phán đoán
- Các nguyên nhân đã xử lý, nguyên nhân nào ko thể can thiệp
- Điều tra cả phía Optinist => mục đích là cải thiện perfomance khi build nên ko nhất thiết phải dựng docker mới điều tra được

**Comment by reactplus-thom** [comment]
@itutu-tienday 
それぞれ、以下の通りに報告いたします。
■調査結果
①確認環境
![357331547_271805495523468_7426769899981898259_n](https://github.com/oist/optinist/assets/135786736/5186e1cf-f51d-47ef-badc-80e46c2b848d)
②処理所要時間
・MRIAnalysisStudio
　Docker環境の場合（startコマンド）：3分程度
　Docker環境でない場合（buildコマンド）：1分程度
　Docker環境でない場合（startコマンド）：30秒程度
・Optinist
　Docker環境でない場合（startコマンド）：30秒程度

②影響する要因
※昨日報告した通りの内容です。
a. ソースのファイル数が多い
b. ソースがtypescriptであること
c. ビルド方法（微妙）

③改善できる可能
c. ビルド方法（微妙）→修正済み、確認して頂いている
※が、これではあまり効率がないかもしれません。

④Optinistの対応
上記2の報告の通りにOptinistのビルドはこちら環境で30秒程度かかることを確認しておりますので、
そこまで改善の必要はないかと思いますが、そちらのご意見などがあればぜひお聞かせください。

よろしくお願いいたします。

**Comment by itutu-tienday** [comment]
@reactplus-thom 
調査ありがとうございます。
そちらの環境では 30秒程度 の起動時間ということで、作業に大きく支障がある状況ではなさそうなので、当件は一旦クローズといたします。

※また必要に応じ、再調査を想定。
