### ISSUE TITLE
ソフトウェアバージョンアップ対応（FrontEnd）

### ISSUE THREAD

**Issue by itutu-tienday** [oist/optinist#530]
optinistのソフトウェア・ミドルウェアのバージョンアップの実施

- バージョンアップ実施作業
  - FE
    - Node.js バージョンアップ (Node.js 20)
    - ミドルウェアバージョンアップ
    - build時の警告の除去（--openssl-legacy-provider, etc）

- 作業手順
  1. 対応範囲の調査、レポート
  2. 上記調査結果のレビュー後、作業実施
  3. 動作テスト実施

- 関連
  - #523 
  - #531

**Comment by reactplus-thom** [comment]
- Thực hiện version-up đối với software/middleware của optinist

- Nội dung thực hiện:

(Ticket này chỉ đối ứng cho phía FE)
+ Version up Node.js
+ Version up middleware
+ Lọa bỏ cảnh báo khi build（--openssl-legacy-provider, etc）


- Các bước thực hiện
1) Điều tra phạm vi cần đối ứng và báo cáo
2) Sau khi phía khách hàng review xong kết quả điều tra **thì mới bắt đầu tiến hành** 
3) Tiến hành và sau đó là test (xác nhận hoạt động)

**Comment by reactplus-thom** [comment]
@itutu-tienday 
調査結果は以下のとおりに報告いたします。
ご確認のほどお願いいたします。
------
基本的には、MRI (https://github.com/arayabrain/MRIAnalysisStudioforMouse/tree/feature/node-18）の対応内容と同様な対応になると思います。

対応範囲としては以下のような想定です。
・Node 17以降ではSSLがバージョンアップされている状態のため、導入しているパッケージに影響がでます。
→@types/react, types/react-dom, react, react-domに対してもNode 18にバージョンアップする必要があります。
・stream, assertのパッケージを追加する必要です。
・react-scriptsはバージョン５にアップグレードする必要あります。
・React18ではdefault typeからchildenが外されるため、Funtionコンポネントのtypeにchildenを追加する必要です。

**Comment by reactplus-thom** [comment]
Version up lên Node.js 20

**Comment by ReiHashimoto** [comment]
resolved in ver1.1.0
