### ISSUE TITLE
ソフトウェアバージョンアップ対応（BackEnd）

### ISSUE THREAD

**Issue by itutu-tienday** [oist/optinist#531]
optinistのソフトウェア・ミドルウェアのバージョンアップの実施

- バージョンアップ実施作業
  - BE
    - Python バージョンアップ
    - ミドルウェアバージョンアップ

- 作業手順
  1. 対応範囲の調査、レポート
  2. 上記調査結果のレビュー後、作業実施
  3. 動作テスト実施

- 関連
  - #523 
  - #530

**Comment by reactplus-thom** [comment]
Thực hiện version up software và middleware của optinist

Thao tác thực hiện:

BE
- Version up Python
- Middleware version up

Các bước thực hiện:

- Điều tra, report về phạm vi cần đối ứng
- Báo cáo kết quả trên kia, sau khi review  ok sẽ bắt tay thực hiện
- Test lại xác nhận thao tác

**Comment by itutu-tienday** [comment]
開発（optinist for server）の中で対応済み。
