### ISSUE TITLE
[No.15]ROIのマニュアルでの削除/追加機能の改善(ROI Edit モード機能の追加)

### ISSUE THREAD

**Issue by emuemuJP** [oist/optinist#535]
現行のROI編集機能の改善（ROI Editモード機能の追加）を実施する

- 設計ドキュメント
  - https://docs.google.com/presentation/d/1Jyp4ZLniev-1YVRt9rTbGxEJqWL3rMMN/

- 補足
  - 設計ドキュメントにも記載あるが、 当機能改修の主要目的は、「操作性の改善（1操作ごとの操作ストレスの改善）」である
  - 基本的に、FrontEndでの実装は高度化・複雑化させず、BackEndを活用することを考慮する（途中計算や仮登録のデータ保持をBackEndで担う、などを検討）
  - 現行のROI編集機能自体の性能改善も実施する（無駄な処理の削減、など）
  - UI実装は、要件に記載の方式は必須ではない。より簡易に実装可能な方式があれば、採用を検討
    - 選択ROIの強調表示や、削除セルの表示、などについて

**Comment by hunghongnam** [comment]
Thực hiện cải tiến chức năng Edit ROI hiện tại (Add thêm chức năng Mode Edit ROI)
- Tài liệu thiết kế (đã dịch trong drive)
- Bổ sung : 
   - Về cơ bản, phần implement của FrontEnd không phức tạp hóa mà hãy cân nhắc sử dụng BackEnd (VD : Sử dụng BE để xử lý việc lưu giữ data cho các tính toán trung gian hoặc đăng kí tạm thời,...)
   - Thực thi cải tiến hiệu suất của chức năng Edit ROI hiện tại (xóa bỏ các xử lý không cần thiết,....)
   - Implement UI không bắt buộc phải theo nội dung tài liệu, nếu có phương thức implement nào đơn giản hơn thì đề xuất vs họ để họ xem xét

**Comment by sanglevinh** [comment]
For deleted ROIs we will give white color, for merge ROIs we will give purple color,
Add new ROI will be blue

**Comment by quanpython** [comment]
@itutu-tienday
BE implementation plan:
- Refactor detected ROI data of 3 wrappers (Caiman, Suite2p, LCCD) to the dataclass which has same structure.
- Refactor edit ROI function to be used for all these wrappers.
- Add ROI:
	- Create mask for temporary ROI  and store temporary ROI ID
	- Return new RoiData
- Merge ROI
	- Merge ROI and store these temporary ROI IDs
	- Return new RoiData
- Delete ROI:
	- Delete ROI and store these temporary ROI IDs
	- Return new RoiData
- Commit Edit:
	- Caculate FluoData for temporary ROIs
	- Remove temporary flag of these ROIs
	- Save NWB file

**Comment by itutu-tienday** [comment]
@quanpython 

Understood.

In addition, do you assume that the following requirements can be addressed by this implementation?

- Improvement of operability (improvement of operation response for each ADD/Delete/Merege operation (about a few seconds for one operation))
  - Some long processing time (e.g., several minutes) is acceptable for the final commit process.

**Comment by quanpython** [comment]
@itutu-tienday Yes, this implementation will solve the problems you are mentioning.

**Comment by itutu-tienday** [comment]
The following are review remarks to the test cases

- Confirmation of commit processing speed
   - Add commit of 10 cells -> completed within 15 seconds
   - Delete commit of 10 Cells -> Completed within 15 seconds
   - Merge commit of 10 cells -> Completed within 15 seconds
