### ISSUE TITLE
GCaMap -> GCaMP

### ISSUE THREAD

**Issue by DeanTM** [oist/optinist#546]
Minor issue, perhaps the default indicator should be GCaMP instead of GCaMap?

https://github.com/oist/optinist/blob/4b5ef789ebd7474ddac165354c694519b0b424dd/optinist/config/nwb.yaml#L17

**Comment by ReiHashimoto** [comment]
@DeanTM 
Thank you for your advice.
We've updated the default indicator from GCaMap to GCaMP in ver1.1.0.
