### ISSUE TITLE
Add support for OPTINIST_DIR data migration

### ISSUE THREAD

**Issue by ReiHashimoto** [oist/optinist#578]
- due to the specification updates in experiment.yaml and introducing workspace id, past version's OPTINIST_DIR data cannot be loaded since version 1.0.0
- add data migration support for past versions, like data migration script.
- also, for the future, add optinist version info into the yaml files (snakemake.yaml, workflow.yaml, experiment.yaml) to detect from which version it was generated.

**Comment by itutu-tienday** [comment]
必要度の点から、一旦クローズ
