### ISSUE TITLE
Rename: ref image

### ISSUE THREAD

**Issue by milesOIST** [oist/optinist#593]
In Visualization, to link 2 visualization modules you have to select the 'ref image'. 
In Optinist context this means select the visualisation module you want to plot. However, this naming is very confusing. Normally 'reference image' is used to describe an image used in motion correction. 

Suggested fix:
rename to something like "Link to module" / "Link to module ID" or "Link to pane" / "Link to pane (ID)"

**Comment by milesAraya** [comment]
Fixed in PR 410
 https://github.com/arayabrain/barebone-studio/pull/410#issuecomment-2292693918
